services:
  app:
    image: kecilin-demo
    container_name: kecilin-demo
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    restart: no
    env_file:
      - .env
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - /tmp/.X11-unix/:/tmp/.X11-unix/:rw
      - .:/app
    command: python src/inference.py