engine:
  onnx_path: weights/onnx/yolov8n/model.onnx
  classes_path: weights/onnx/yolov8n/metadata.yaml
  score_threshold: 0.1
  conf_threshold: 0.4
  iou_threshold: 0.4

source: tmp/ambulance.jpeg
save_path: output
mode: image
show: true
device: cpu